### PR TITLE
refactor: assert moduleExports

### PR DESCRIPTION
**Pull request by rtritto**

### CODE REVIEW

**Comment by brillout** [comment]
It's on purpose. I really think we should focus on features instead of internal refactoring :)

**Comment by brillout** [comment]
> on features

I can share you our list of current priorities if you're interested.

**Comment by rtritto** [comment]
> It's on purpose. I really think we should focus on features instead of internal refactoring :)

During my analysis, I found a minimal and simple refactor. Improve the readibility and the code, should always be accepted.

> I can share you our list of current priorities if you're interested.

Sure, I can take a look.

**Comment by brillout** [comment]
> > It's on purpose. I really think we should focus on features instead of internal refactoring :)
> 
> During my analysis, I found a minimal and simple refactor. Improve the readibility and the code, should always be accepted.

These two `assert()` calls often fail. When this happens I want to know which one of these two fails simply by reading the stack trace, that's why deduping them is actually a regression. As I said before: please trust us with internal stuff :slightly_smiling_face:

> > I can share you our list of current priorities if you're interested.
> 
> Sure, I can take a look.

How about one of the following?

- https://github.com/vikejs/vike/issues/1715
- [New Bati integrations](https://batijs.dev/)
- https://github.com/brillout/handli/issues/6
- https://github.com/brillout/telefunc/issues/103

WDYT?

**Comment by rtritto** [comment]
> These two assert() calls often fail. When this happens I want to know which one of these two fails simply by reading the stack trace, that's why deduping them is actually a regression.

Good to know 👀

> As I said before: please trust us with internal stuff 🙂

Of course. Anyway I/we can't know whether the code is correct or not, so trying (eg with PRs) may lead some positive results. Any help can bring improvements or innovative thoughts; also useful to the community since we are all moving in a common direction.

> How about one of the following?
> 
>     * [New Vike Extensions vikejs/vike#1715](https://github.com/vikejs/vike/issues/1715)
> 
>     * [New Bati integrations](https://batijs.dev/)
> 
>     * [Polish handli#6](https://github.com/brillout/handli/issues/6)
> 
>     * [Automatic UI handling of network issues #103](https://github.com/brillout/telefunc/issues/103)
> 
> 
> WDYT?

For the Bati integration, I created [solid-jotai](https://github.com/vikejs/vike-integrations/pull/3).

For Jotai integration, a new Vike extension is needed?

The two points of Handli and Telefunc aren't on my scope at the moment.

**Comment by brillout** [comment]
> For the Jotai integration, a new Vike extension is needed?

:+1: Sounds good, let's give it a try. How about for React i.e. `vike-react-jotai`?

**Pull request closed without merging**
