### PR TITLE
added simple svelte-kit example

### PR DESCRIPTION
**Pull request by doeixd**
I added a simple svelte-kit example based off the vite-plugin-ssr example

Sorry about all the commits, I made this using stackblitz, then copy-pasting it into the github editor, so the formatting was a bit wonky

#14

### CODE REVIEW

**Comment by brillout** [comment]
👍 Let's merge this after I fix SvelteKit + Telefunc building.

**Comment by magne4000** [comment]
FYI this doesn't seem do work anymore with latest sveltekit + vite versions.

**Comment by brillout** [comment]
Maybe I'll have time to have a look at this next week. Let's see.

Feel free to comment here if someone wants to use Telefunc with SvelteKit sooner rather than later.

**Comment by magne4000** [comment]
I think I understand why I have an issue.

[Some illegal imports are checked in the `config` hook](https://github.com/sveltejs/kit/blob/73fe63b3c196dc8cb984fda9e394377bea50d479/packages/kit/src/vite/index.js#L193-L196), so before [transform](https://github.com/vikejs/telefunc/blob/master/telefunc/node/vite/transform.ts#L18) is executed.

If I manage to avoid those illegal imports, `telefunc` seems to work as intended. Seems like a svelte-kit issue to me then.

**Comment by brillout** [comment]
I see. Although I wonder: Telefunc's `transform()` has `enforce: 'pre'`, so I would have assumed that it runs before SvelteKit's inspection?

**Comment by magne4000** [comment]
They use [metadata information](https://github.com/sveltejs/kit/blob/00fbfeb2f10f94bf13793ac75fcbdb1376e65401/packages/kit/src/vite/dev/index.js#L67) to check the dependencies it seems. Perhaps it's not cleaned up after a `transform` (I'm still not familiar enough with vite/rollup internals)?

**Comment by brillout** [comment]
Hm, I'd need to have a closer look. Thanks for the update.

**Comment by magne4000** [comment]
I tried to dig further, but it's not obvious at all. Also I noticed another issue: During a `vite build`, `svelte-kit` uses `.svelte-kit` as `build.outDir`, but having `telefunc` as a vite plugin makes output janky, as some files are generated to `.svelte-kit`, but some are still generated to `dist` folder

**Comment by brillout** [comment]
Ineeded Telefunc should respect `build.outDir`. That's an easy fix though.

**Comment by brillout** [comment]
@doeixd SvelteKit has been refactored to be more compatible with the Vite plugin environment. I believe you should now be able to use Telefunc with SvelteKit. The only culprit is https://github.com/sveltejs/kit/issues/6700 but there is a PR for it https://github.com/sveltejs/kit/pull/7288. Up for update the PR to the latest SveteKit version?

@magne4000 The build issue is gone, right? If not, let me know because AFAIK it's an easy fix on Telefunc's side.

**Comment by brillout** [comment]
Seems like this PR doesn't have a champion anymore. Closing. A new PR adding a SvelteKit example welcome.

**Comment by magne4000** [comment]
Once Rich pushes a fix on sveltekit I get back to this

**Comment by brillout** [comment]
👍 Looking forward to.

**Pull request closed without merging**
