### PR TITLE
`typeToShield.ts` error upon upgrade typescript

### PR DESCRIPTION
**Pull request by brillout**
Hi @louwers, I'm trying to upgrade to TypeScript `5.5.2` but I get following error about `typeToShield.ts`.

image

Do you have a suggestion for how to solve it?

I hope you're well!

### CODE REVIEW

**Comment by louwers** [comment]
Seems to happen with 5.4.5 first in the playground.

https://www.typescriptlang.org/play/?ts=5.4.5#code/C4TwDgpgBAogjgVwIYBsDOAeAGgGigTQD4oBeKACgwBVDyBKU4qqCAD2AgDsATNKLKAH4oARigAuKACYGbDjz7VaDEkxbsuvAkNETpO4ACcE0SQDNUaCAChroSFACqnAJYB7TlTcBJTh0NWAMbA7pxKpBTMcpp8zMLkYEiGSAC2aJJUKsRInCB6nBAAbhCGshoKFInJaZIunGYlUAAKWVA5ecJN+UUltgD0fVBghhDAISUAtC4A5pxuI9YDUABG7ikQU7Pz0GbzKUjA4nbg0M6hXlQIYCgQ1HgAShB80RXtANoAuhGfxGRnHl5fP4giEPBhrFAoFFylp2jp6Iwod1ioZrMQXloEaooHUGoYoI9gAhDJ4ThCdP9PG5LtdbjBWIEUAhuLcqA9RsTSZBCHg3gA6AWPNDsokkqgnD6EcmSIW2ezQADKAAsXBAUNwhRgFep5Fo0EY6tM8ABBQKBHUxKD6wyGz7fSURADe5OtkgV5KQZskpsC1gAvv1BsNRuNDJs5gslqs3Otw9soLtDPtDscHAqXClaeLIHcoD6La9cnayD8IvBkOhc9bDeiYXwjCZycJlar1ZqAOQAfU7HBuZgQnECPb51c403bJrNUshknLllznAQKWWJVruvrxhskObKrVGqeGC7PbVEH7g+Hi+XJQnean0tgiHnbJWbjcNxya8tDa3Ohbe473a9qeA5DsAfLLK+76cDePrTnoc6Vs+AAiBwQJ+FTfk2UB-m2B5HkBZ6gXy3CoTBd4zg+FaYM+7ToVomHbthu64Zg+EnoRw7tGRgRweYlg2IsQYjGMqphjMEY2FGawbOJ8aJsmRzygSEDXJ6EDGigKBagWeoGmOeAAGKGDGOl8KORpQm4plWnp0y-FARkmRifDtu2WHuhR2rOVAAAGAAkjq4o0ABCp7bH6AWOSkEWBfUjTGmY-h+j5WH+Y6oWJhAMVeDFjyqYE6maRgCX+IZxkpHgXiEMl97uoJQzCaGcaRoM0axrJIwJnsByKScUAADIuP4qC5vm3nvA6ZDQuuNk2mO7nMfumA+YB7EgcOgQePq5DtgFeUoGpGlac+ABE7YnXgJ0ADpXed1XtnQPmTjx97TZaEFvhAOQLa2S0YCtx59utYGbZw20BVQfqPc9vFIt5l4rqijE4X9AMEcDfKg+DjqQ9Dt4vRRFjoAJSkAFJuHUEDcNQ1kTc9tNFh8eCDfqEQoyzwBKHgpMROTdQo0KHMYBzhD2Tz3nmT9-4HqTMP3gUKKBg1Iaic1kmtdJatdUmPWptAxqGMkICDQA1qyDMgJ89PjYz9r2W9FT8gKQX4o4HxYQhmCOG87Y3GOwBKu2TNQAjq7WQxkI6A7mIu1AABqdCfOSke-otGBx7y7ZJEbN4CnyPqSsnkeSArvQp26i1C44dF8ALB7tHgtFJynwh8wU1OOJnRK0rnAoF3BFGl0jyK9HrUBt48m2GNT0d8JP8zU+ZeB15gDdtLkovW3W6+W5NTG-Zq5JtwqtmYEXlIXFcNzginkLOrfkdvAA0jinCwOwyTBBgZsgG4ZhQngcyhAPiSDSk-P0kgAoAHVkhgBXtQZ+koaoPz9G8ekRhPScx-n-ABs0azuxTnBHk5IfaOj9L3fOZp3ZSjHnXKeM9rLz2nhgJeO9RZOhIS-Oo78MFf2wf-Z8QC2h8CfiA-ee4EGiKlAGeqwYRKTA6urFYmtFHawUmPJ+EAQBx1QCYeBs9lL0JYbZRuG8t4zQmvZOhC9wjeSYdTNetEsITwgEY6xzCaBy0Hj0VEsjGqq0UfVNqMktidXkrrJSmjtG6IgAAeUMLE5YAArVxwAUY0zsa4mxrDaLmMtJYiIBj7EYFjk-PAsc45wWEJ7DAZS8FjhrlACOyM04ZygD7NwyTUkUP7kXSQUSdFMggPorxegBkxJGfjGhSw5FNUCVJGMISJJqIiX1dJz4xrbwmnbNmGYswnFsdveBTjkZ7JuNmVkozJADhZGYSm3BrJUCluqDA9JGTMkuVAG5p57k8nae2NwYBQScFQD0qhsNFyaUec86mbymQsgXAgTSfyfaQoOssG4YLAiFwot4NAlJDkzQjjuX6BKNnkT0AYiaWEDZG1Np82Cr1GFZOYY4jeWFxlDPiYklJwR1lXPaYNYax0YZfG8m8Y5uRTEgGAVhIVJQRrkoJiPXxMz-EKNCUo4JWtwkpiUijMleTCy7ysZXFw+oMAX2pFfVk7DvKSpANKwgzcdBtyppa1wAJrW0i5v8gcoQsU4pVXKPqeKyX2TeFQMV283hWqBCUEEoQlBfGEETKwehMJ+JVhqiSQSVGapWXqvqMCkBgAydvVhUSADuC97LVoXtZdsaKkAYogG5RiaM1rnjAs21t5AIZQxShRet09G2AuBaC1Kq0gbdr5OO0IqB+040HfeEdDzvLtm7piqdgNgKzq3RAJduMh1jK0TW0dG7s5IBAO2nQnaZ1ESvSAI9K7h1nobRusht7hA+UdFAAdUBkGnpAOe9d292z+o8N+3y0691EXmC+x6q730XvA503lwBoP3rg8OdDqTEMnoyErWZATNV5sWTq7qRaHAlrgYtTUBiHVOvttZeBscFTlLiviRljFNkzTeLHAAEl9bgeA86xyoEgFwKACGR2EJJ6TFsXUtygLR+B8DaNajwMJpA3A-kKZQKLIu3jFbl2wvLHxIa0wqXCFNRt7YdCuT0DeNyY9j70aeELJV1lzIRFcix8VQmRNiedlxqEUmZNYR02BmaTG2FF3kxF1jHnV5SrYcpuT48KacBXl5iLeA0o+higqGzsEYpqZSxgaL1UfID2LvjPpDWKI+is4qM1FqqWM3stFwlloh46DtJICVaces0D+Xndm5rOYGaULKtz2WT5zWmNRJTwc+OWl82QfzhTrICbC9FkLfIJMRdk8IaLPnbIJay-zU+1B8u+QCkVgKJWy1lYCtF5KdXvRmnvC12hi1Fu5iFGzNOY2IjA-tZVtlMqdAVYPgeIUxAS6WesGwMA8xgBNL6jN-qq37K4+8iMXTHgUB5DtMIQbA1rJE+4CTsn7RBCHdjv1AzKaBoGb0EnVHrB0eGEx0pHrBOtldYiP1H2ftpgByDtZAADDofrkgxcy-dv936i2ACypby0WJF2QUbjT+sU6+ENouKNAf6+ISnCbAOjCa7LTNsb1gVdo4x1jtMi1aWA867vPA6uQdq9t1rsHZA-c213net4AVj63fV9VD4Plg1j07IEJAVg+AlnJPSSAX8alm6MMYpbfy2IPuHOZdsm9M889Sa8x8lY8+GAwKHQwRfYMcR7UuRG5fLfv2z5zXPNuG8fSgi33dbfwKQS+tBCvkIs-V-7wHhvKEOAj-RrOkiHAu84Er73mvVEtQD4wLkqAxecNgS4tPnvc-a+YHrwXw0UAAA+IckWGbwCfsfvabjkFbxjcydBN-b5X57636+ZP7fJ3Ltwr5drwZAoLooDf6j6-62T-4X6z5fxFzz57iA5N6P7P5QpgE8A-KQFv4-6zrzoeCLqkFESf6HpUEXgd4lB0AoHkjd5oF97X774L4YBiBP5opQEl7t6aQtpf50EgxbTADkAiBMEAEz5V454cG348FfKEEQFUz8Gn5zqwEUHwGiGYziGSHSGoFyHsHAEH5vBN54BD6T6SgkGIH7o2oIGr7UEMGGB4C6FWE5AoGsHGE3yRyezGi5CxJmC+Epy37mEuGM4vifQ5CCA2HGbtLxGQjv4YwHqOHQG4ZaEgo6F2HOFXilBuE5EZETrZFOHDgeGcDSFb4PxJG6GpG6HkFZFpECHj7REVEFGlFgQNGUGFHt55HSHxGyaQhEJVGX7oEpz+GBHBHxG34AoFAOZP6bo1rl4jEpxvCJFQAnT1GGBNEaFYwSGLFuAPTtHpFiFgz7EeBtpMEXTrGbE9FzrbG6F7E7QXFHFQCPH6EHEPR0AnQDFFzDGAFjF+HX4BEgBBEhGRyKG4FSC4HgG-IrGPzrHJFkGZHdEdH3E7Fj5PEyDHHNFPFSGVGIn1EoklEnHonvFnEGE4m7H6EyD9EPyDFQD-GyE74YHAmTHgmQi344FP5ALwmQhrHVHH5bEYkYwWFvF3F-4TiEl3EIa6GsK6FN7-6-GEIsEjFsG77zhckuE-C2FolPoimzqKkyGjGcysl77TFmFinmQfA6nxFImPqGzXoGlER1F3FilynIFKkqlDFqk+FmmakH5-pIDTAQAlwuEADcUASoqewULgZskg5RgGRef60ZaAsZ8Z4paJ5RjcIZkgCpLhgG5eqpAJpp4xHBFpXBQZuZz+eRkZqZ6ZEAggCZE+OQSZfJx+KZMZcZoZmZpJXRJJzR5RdAOZPZ+ZeRhZfxxZzJQBAZXBm6TwmGfytxaJTx85+oD0J0RhO+mB6ogOZ0HA65m5l05J207YN0a5wA55G5W5M5deB+346hmJ+h34Xhvp25ChB+aaaEuppJTxX5r5JZGpd5XBIgUgAAzI+RjHieBQBdOYCTPuWQ-Lfn+uagAOKvjcDNmtGAa4G8l2nCkoVoDoVuCYW9mDktlvx+hUlj6SmTk+mAU7ncCA5Vk9k4GoI2FCl3H6ksV5lukFlQzGnqmMWA7FKsJN6bycVol4bBDOn0F9GCV+llnmlIUH6iUmJQAsVNk1mIxJnd4pz2m4ZdIyU8VkUaH9myW9GIwMACV0WMlvm3k36qUsqLzqXiU6mSWkn6n1FGUSFjlWWwUmlAWOW-Se755vBiUuEcXthvAelLbUWimRUKXvmmEhWGyA7hF5GxFF4xUynEkWV8iKkfBJXV7+mVgVl7ihUN7hWuURGAK2RZXtnRWxWGjxXInFH5WKmtUwHtXNVjh0BFW2VSjuxKTqkGIPmFJjwTGgnBHPhC464mqi67ZBa6ZM5has4ewcHPjVbhybhXbNLwRsnTW5gGawxfnWBAA

**Comment by brillout** [comment]
Indeed it doesn't happen with `5.3.3`.

> I can have a look next weekend.

:+1: That'd be great! Let me know how it goes, I can give it a try as well (I had a look already but I ain't sure yet what I can change, I'd need to dig more into the whole logic works).

**Comment by brillout** [comment]
> force-pushed

Just rebased on top of main, nothing changed.

**Comment by brillout** [comment]
Fixed by https://github.com/brillout/telefunc/pull/125.

**Pull request closed without merging**
