### PR TITLE
refactor: improve fixStacktrace in vite.ssrLoadModule

### PR DESCRIPTION
**Pull request by rtritto**

### CODE REVIEW

**Comment by brillout** [comment]
Thank you @rtritto

**Comment by brillout** [comment]
Btw. in case that's something you'd be up to, we're looking for help to add new tool integrations to Bati. How does that sound to you?

I feel like this would be more gratifying for you than refactor contributions. (Refactor contributions can be problematic as we've seen in the past :slightly_smiling_face:.)

@magne4000 Are there low-hanging-fruits for new Bati integrations?

**Comment by magne4000** [comment]
We could start supporting [internationalization](https://github.com/vikejs/bati/discussions?discussions_q=is%3Aopen+internationalization) in Bati.
Beside that, Kysely integration could be great too, but I see it being rather difficult to properly implement.

**Comment by brillout** [comment]
Or maybe adding https://vike.dev/extensions#react and/or tools from https://github.com/vikejs/vike-integrations.

Also, contribution welcome to research and add tools the list https://github.com/vikejs/vike-integrations.

> We could start supporting [internationalization](https://github.com/vikejs/bati/discussions?discussions_q=is%3Aopen+internationalization) in Bati.

I think it's better if we wait for https://github.com/vikejs/vike/issues/1000.

**Pull request merged**
